### PR TITLE
Add imperative handle

### PR DESCRIPTION
**Pull request by kayyali18**

### CODE REVIEW

**Comment by monsterkrampe** [comment]
https://github.com/davidjbradshaw/iframe-resizer-react/pull/53

**Comment by kayyali18** [comment]
@monsterkrampe 
Yes, I wanted to test your solution on something I'm working on, and considering the PR hasn't been merged in ages I forked it and attempted to use it locally.

Thank you

**Comment by monsterkrampe** [comment]
I saw that you also published a npm package with this fix so I just mentioned this on the original PR because I think that this may also come in handy for others :)

Keep it up!

**Comment by kayyali18** [comment]
It's all you 😅
But thank you

**Pull request merged**
